# Generated by Django 3.2 on 2025-05-14 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название меню')),
                ('menu_name', models.CharField(help_text='Имя меню, к которому относится этот пункт', max_length=50, verbose_name='Название меню')),
                ('named_url', models.CharField(blank=True, help_text='Именованный URL из urls.py', max_length=100, verbose_name='Именованный URL')),
                ('url', models.CharField(blank=True, help_text='Явный URL (если нет named URL)', max_length=200, verbose_name='Явный URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок стортировки')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem', verbose_name='Родительский пункт меню')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['order'],
            },
        ),
    ]
